services:
  db:
    image: postgres:15
    container_name: db-signlink
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${BACKEND_DATABASE_ROOT_USERNAME}
      POSTGRES_PASSWORD: ${BACKEND_DATABASE_ROOT_PASSWORD}
      POSTGRES_DB: ${BACKEND_DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  back-end:
    build: ./back-end
    container_name: back-end
    restart: unless-stopped
    env_file:
      - ./back-end/.env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./back-end/uploads:/app/uploads
      - ./back-end/kamus_videos:/app/kamus_videos
    depends_on:
      - db

volumes:
  db_data:
