# Redirect HTTP -> HTTPS
server {
    listen 80;
    server_name devanadindra.site www.devanadindra.site admin.devanadindra.site;
    return 301 https://$host$request_uri;
}

# Frontend utama + API
server {
    listen 443 ssl;
    server_name devanadindra.site www.devanadindra.site;

    ssl_certificate /etc/letsencrypt/live/devanadindra.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/devanadindra.site/privkey.pem;

    # API proxy
    location /api/ {
        proxy_pass http://back-end:7777;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri /index.html;
    }
}
